#!/bin/bash

if [ $# -eq 0 ]
then
	echo "assuming device /dev/ttyUSB0"
fi
stty -F ${1:-"/dev/ttyUSB0"} 9600 min 0 time 0 -parenb -parodd -cmspar cs8 -hupcl -cstopb cread clocal -crtscts -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8 -opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0 -isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt -echoctl -echoke -flusho -extproc
tail -f ${1:-"/dev/ttyUSB0"}
